### PR TITLE
Minor changes to Section Recommendations using the PIDINST metadata schema

### PR DESCRIPTION
**Pull request by RKrahl**
Make minor changes to Section "Recommendations using the PIDINST metadata schema":

+ Despite the title "Using other PIDs" this subsection only discusses RRIDs.  Add an introductory paragraph mentioning also other relevant PID types.
+ Reduce excess width of Table 5.1.: add line breaks in the `Type` column, reformat the `Description` value in the `Data` column.  As a result, the user needs to scroll less horizontally.

This PR depends on #4 because it modifies the section that has been moved in this other PR. It has been based on the `schema` branch to avoid a conflict.  Nevertheless, the changes are independent of that PR.  It may be rebased onto `develop` if desired.

Check the [result on RtD](https://rda-pidinst.readthedocs.io/en/schema-rec/white-paper/metadata-schema-recommendations.html).

### CODE REVIEW

**Comment by louatbodc** [comment]
To be referred to main co-authors before closing

**Comment by kitchenprinzessin3880** [comment]
{
  "identifierValue":"http://hdl.handle.net/21.T11998/0000-001A-3905-F",
  "identiferType":"MeasuringInstrument"
}

@RKrahl @louatbodc is the above example, is the idenfierType MeasuringInstrument or handle?

**Comment by RKrahl** [comment]
> {
> "identifierValue":"http://hdl.handle.net/21.T11998/0000-001A-3905-F",
> "identiferType":"MeasuringInstrument"
> }
> 
> @RKrahl @louatbodc is the above example, is the idenfierType MeasuringInstrument or handle?

That is the issue that the first bullet point in #3 raises.  I suggest that this example is not conform to our schema and that the value should be "Handle" in this case.

**Comment by RKrahl** [comment]
Merged and thus adopted #10, so this PR will now also make a small change in the introductory paragraph of the section.

**Pull request merged**
