### PR TITLE
Adding B2INST to 'adoption'

### PR DESCRIPTION
**Pull request by tkalman**
This adds _B2INST_ as an adoption story.

### CODE REVIEW

**Comment by RKrahl** [comment]
@tkalman, do you want to be added to the author's list?  Ref. #26.

**Comment by RKrahl** [comment]
I enabled building that branch on Read the Docs. So you may preview the [result of this change](https://docs.pidinst.org/en/adoption_b2inst/white-paper/adoption.html#b2inst).

**Comment by markusstocker** [comment]
Minor some spelling perhaps, to me this looks good. Can we merge @louatbodc?

**Comment by louatbodc** [comment]
Looks good to me. Please merge

**Pull request merged**
