### PR TITLE
Datevalue json

### PR DESCRIPTION
**Pull request by louatbodc**
Reverting date property value name in ePIC handle record.

1. Corrected JSON example
2. Corrected table 5-1

### CODE REVIEW

**Comment by RKrahl** [comment]
Looks good for me.

A remark for the discussion: the schema doesn't specify the details of the serialization of the metadata.  So whether this field in JSON is labeled `date` or `dateValue` is left to be determined in the implementation. Either version would be acceptable in my opinion. But your new version is somewhat more consistent with `AlternateIdentifierValue` and `RelatedIdentifierValue`, so it's indeed an improvement. There are still minor inconsistencies regarding capitalization, though: `dateValue` versus `AlternateIdentifierValue`. But IMHO that should not stop us from proceeding.

**Comment by louatbodc** [comment]
I can see a few other cases have changed. It will be relatively quick to adapt them in the JSON and table 5-1. @RKrahl Should I proceed with the changes?

**Comment by RKrahl** [comment]
As you see fit.

**Comment by louatbodc** [comment]
Done in https://github.com/rdawg-pidinst/white-paper/pull/18

**Pull request merged**
